spring:
  application:
    name: payment-process
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serverUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
